worker_processes 1; # ilość głównych procesów roboczych

events {
    worker_connections 1024; # ten jeden proces może obsłużyć do 1024 połączeń na raz
}

http {
    server {
        listen 80;

        # łapiemy każdą ścieżkę, /health /notes ...
        location / {
            # przekierowujemy na port 8000
            proxy_pass http://backend:8000;
            
            # $host to wbudowana w Ngix zmienna przechowująca oryginalną domenę o którą zapytał klient
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr; # podpiecie adresu IP użytkownika
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}